# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qrious', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.CharField(blank=True, default='Answer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Qrious.Player'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_no',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
