# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qrious', '0002_auto_20170314_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='solved',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='user',
        ),
        migrations.AddField(
            model_name='player',
            name='answers_given',
            field=models.CharField(default='0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='question_no',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
