# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qrious', '0003_auto_20170316_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
    ]
