# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Qrious', '0004_remove_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
